"""update admin table

Revision ID: 220f35d8ac4a
Revises: f37135429ca4
Create Date: 2023-02-19 16:31:20.248739

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "220f35d8ac4a"
down_revision = "f37135429ca4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "avatar", existing_type=sa.BLOB(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("admins", "avatar", existing_type=sa.BLOB(), nullable=False)
    # ### end Alembic commands ###
