"""adding admin table

Revision ID: 93fe600f2e9b
Revises: 2b7380507a71
Create Date: 2023-02-19 15:44:33.633886

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "93fe600f2e9b"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=False),
        sa.Column("hashed_password", sa.String(length=300), nullable=False),
        sa.Column("avatar", sa.LargeBinary(), nullable=False),
        sa.Column(
            "date_creation",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "dummy_model", "name", existing_type=mysql.VARCHAR(length=200), nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "dummy_model", "name", existing_type=mysql.VARCHAR(length=200), nullable=True,
    )
    op.drop_table("admins")
    # ### end Alembic commands ###
