"""update admin table

Revision ID: b59b10649336
Revises: 220f35d8ac4a
Create Date: 2023-02-20 11:42:00.656549

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b59b10649336"
down_revision = "220f35d8ac4a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins", "name", existing_type=mysql.VARCHAR(length=200), nullable=True
    )
    op.create_unique_constraint(None, "admins", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "admins", type_="unique")
    op.alter_column(
        "admins", "name", existing_type=mysql.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###
