"""update admin table

Revision ID: f37135429ca4
Revises: 93fe600f2e9b
Create Date: 2023-02-19 16:30:30.878887

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f37135429ca4"
down_revision = "93fe600f2e9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins",
        "date_creation",
        existing_type=mysql.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("current_timestamp()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "admins",
        "date_creation",
        existing_type=mysql.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("current_timestamp()"),
    )
    # ### end Alembic commands ###
