"""update admin table

Revision ID: f48827a8a003
Revises: b59b10649336
Create Date: 2023-02-20 12:35:23.750869

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f48827a8a003"
down_revision = "b59b10649336"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("admins", sa.Column("disabled", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("admins", "disabled")
    # ### end Alembic commands ###
